### Vagrant Development Environment for grideditor
#===============================================================================
#
#   Brings up a testing server ready to use that will run at http://localhost:8881
#
#   phpMyAdmin can be accessed at http://localhost:8881/phpmyadmin
#       username: root
#       password: password
#
#   SSH into the box by running the command `vagrant ssh` from the project root
#
#   MODx manager login is at http://localhost:8881/manager
#       username: admin
#       password: password
#

#### Configure Vagrant ==========================================================
###=============================================================================
Vagrant.configure("2") do |config|

    config.vm.define :vagrant do |vbox_config|

        ## Box Definition ######################################################
        vbox_config.vm.box = "precise32"

        ## Network Binding #####################################################
        config.vm.network :forwarded_port, host: 8881, guest: 80

        ## Shared Folders ######################################################
        vbox_config.vm.synced_folder "../../core/components/grideditor", "/var/www/core/components/grideditor"
        vbox_config.vm.synced_folder "../../assets/components/grideditor", "/var/www/assets/components/grideditor"

    end

end
